(global-set-key (kbd "C-x w") 'whitespace-mode)
(global-set-key (kbd "C-c a") 'org-agenda)
(global-set-key (kbd "C-c c") 'org-capture)
(global-set-key (kbd "C-<tab> <tab>") 'hs-toggle-hiding)
(global-set-key (kbd "C-<tab> h") 'hs-hide-all)
(global-set-key (kbd "C-<tab> s") 'hs-show-all)
(global-set-key (kbd "C-;") 'yas-expand)
(global-set-key (kbd "<up>") nil)
(global-set-key (kbd "<right>") nil)
(global-set-key (kbd "<left>") nil)
(global-set-key (kbd "<down>") nil)

(provide 'init-keys)
